### ISSUE TITLE
Stalls on login screen

### ISSUE THREAD

**Issue by boynedmaster** [CloneTrooper1019/Roblox-Studio-Mod-Manager#11]
Ever since the Studio makeover, this no longer works for me. It gets stuck on this screen.

![](https://i.imgur.com/7Z0dzCy.png)

However, running Roblox Studio on its own works perfectly.

**Comment by CloneTrooper1019** [comment]
I'll look into this.
I think you should be able to open a new place through the File window though.

**Comment by boynedmaster** [comment]
Yeah probably, but I don't think I can edit my online/group places with that (and I don't want to have to Ctrl+S my places, SetPlaceId so data stores can work, bla bla bla).

**Comment by CloneTrooper1019** [comment]
Are you able to launch those places from the website?
Alternatively you can disable the new login screen all together by applying this FVariable configuration: 
![image](https://user-images.githubusercontent.com/3926900/31579842-d6bc9358-b104-11e7-8ae1-920c1e5f5feb.png)

**Comment by boynedmaster** [comment]
I'll do the FVariable thing, but what do you mean by being able to launch those places from the website?

**Comment by boynedmaster** [comment]
Because of this and #12, this program is now useless until this is fixed.

**Comment by boynedmaster** [comment]
I'm attempting to solve this issue, but to no good results. The issue is not because RSMM doesn't have the right command line arguments.

![](https://i.imgur.com/DB8wdXP.png)

**Comment by EchoReaper** [comment]
In regards to disabling via flags, as of ~314 disabling the new studio layout triggers a crash whenever a place is opened. The window size also doesn't save anymore. It seems they cut a bunch of old content which broke installations using it through flags. 

Luckily I don't seem to be experiencing this infinite start screen anymore, and I assume that's the case for the reporter as well, so this can probably be closed. Unfortunately, native UI is still awful.

**Comment by boynedmaster** [comment]
Nope, I still get the infinite login screen.

**Comment by EchoReaper** [comment]
@boynedmaster If you click File > About Roblox Studio, what version is it? Studio Mod Manager has not been updating Studio recently (Roblox changed endpoint?), so you're probably on an old version.

**Comment by boynedmaster** [comment]
I'm not home to check, but I've done everything to get RSMM to reinstall Roblox Studio (Force client rebuild, manually edit the registry, etc) and it still hangs.

**Comment by boynedmaster** [comment]
(accidentally pressed Comment) ...so I'm certain I have the latest version of Studio.

**Comment by EchoReaper** [comment]
Please include a link to a screenshot of your About Roblox Studio screen when you get home.

**Comment by boynedmaster** [comment]
@EchoReaper ![](https://i.imgur.com/omgiR5D.png)

The left is RSMM, the right is Roblox Studio. They both are the same version.

**Comment by CloneTrooper1019** [comment]
@EchoReaper Roblox did change their versioning protocol recently, I'm going to be updating my programs to reflect this soon.

**Comment by CloneTrooper1019** [comment]
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/7241bf65ee7abee6dd8ad1869f5bc1fa84462da8

Check out this new build and see if anything is different. It uses the new version-compatibility system that Roblox is using for version uploads.

I fixed some bugs and updated the installation protocol to be up to date with everything in studio. There was apparently some platform-fonts zip file that I wasn't adding. I'm not sure if that was affecting anything with the login screen.

**Comment by boynedmaster** [comment]
@CloneTrooper1019 This did not fix the issue.

**Comment by CloneTrooper1019** [comment]
@boynedmaster Alright, after doing some deeper investigation I think I specifically know why this is happening now. I'll try to have a patch out later today, once I can isolate why this problem is happening. 

Here is a temporary fix:

* Launch Studio through the "Just Open Studio Path" mode
* Go into the downloads folder
* Open Qml.zip
* Copy the folder "QtQml" and paste it into the Qml folder in Studio's directory.

**Comment by CloneTrooper1019** [comment]
@boynedmaster Alright, after doing some deeper investigation I think I specifically know why this is happening now. I'll try to have a patch out later today, once I can isolate why this problem is happening. 

Here is a temporary fix:

* Launch Studio through the "Just Open Studio Path" mode
* Go into the downloads folder
* Open Qml.zip
* Copy the folder "QtQml" and paste it into the Qml folder in Studio's directory.

**Comment by boynedmaster** [comment]
Not home, but will try when I get home.

**Comment by CloneTrooper1019** [comment]
Should be fixed with this commit?
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/commit/ab855e74b51c79ae9cbd239668b91fa8e7e05991

**Comment by boynedmaster** [comment]
@CloneTrooper1019 The commit didn't fix it, (maybe because I already had the Studio installed), but your "temporary fix" did. Good work as always.

**Comment by CloneTrooper1019** [comment]
@boynedmaster If you force the reinstall with the newest version, it should work I think.

**Comment by Mirza-97** [comment]
@CloneTrooper1019 
Thank you for solving it for me. I'm back to work finally.
What happened before was Studio crashed randomly when playtesting a place "solo."
Then the next thing you know, it wouldn't log on.
I could have tried rebooting but I was lazy and therefore the Mod Manager fixed it for me.
